name: connect
description: "Dating App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  logger: ^2.5.0
  shared_preferences: ^2.3.4
  provider: ^6.1.2
  flutter_otp_text_field: ^1.4.0+2
  step_progress_indicator: ^1.0.2
  flutter_floating_bottom_bar: ^1.2.1+1
  getwidget: ^5.0.0
  modal_bottom_sheet: ^3.0.0
  flutter_svg_icons: ^0.0.1+4
  http: ^1.2.2
  buttons_tabbar: ^1.3.15
  location: ^7.0.1
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  timeago: ^3.7.0
  intl: ^0.19.0
  web_socket_channel: ^3.0.1
  flutter_animate: ^4.5.2
  swipe_cards: ^2.0.0+1
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets: 
      - assets/
      - assets/svgIcons/
      - assets/dp/
      - assets/fonts/